"""adiciona coluna replicar_mensal em custos_fixos

Revision ID: 025c3252e0d2
Revises: 2a00e7341633
Create Date: 2025-11-13 12:10:37.641861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025c3252e0d2'
down_revision = '2a00e7341633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custos_fixos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replicar_mensal', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custos_fixos', schema=None) as batch_op:
        batch_op.drop_column('replicar_mensal')

    # ### end Alembic commands ###
