"""Adicionar modelo Compromisso

Revision ID: 2a00e7341633
Revises: fbb7163c56be
Create Date: 2025-11-13 11:07:52.113120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a00e7341633'
down_revision = 'fbb7163c56be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compromisso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.String(length=20), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('membro_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['membro_id'], ['membro.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compromisso')
    # ### end Alembic commands ###
