"""Criar tabela configuracao para financeiro

Revision ID: 978ad2794883
Revises: a03184021fbf
Create Date: 2025-11-09 12:52:50.544614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978ad2794883'
down_revision = 'a03184021fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provicao_extras', sa.Float(), nullable=True),
    sa.Column('salario_medio', sa.Float(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracao')
    # ### end Alembic commands ###
