"""Versão inicial completa

Revision ID: e9235ee2a81c
Revises: 
Create Date: 2025-11-16 11:22:48.801763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9235ee2a81c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provisao_extras', sa.Float(), nullable=True),
    sa.Column('salario_medio', sa.Float(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao_financeira',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_dizimistas', sa.Integer(), nullable=False),
    sa.Column('valor_meta', sa.Float(), nullable=False),
    sa.Column('data_configuracao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custos_fixos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('replicar_mensal', sa.Boolean(), nullable=True),
    sa.Column('mes_referencia', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('imagem', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('estado_civil', sa.String(length=20), nullable=True),
    sa.Column('conjuge', sa.String(length=100), nullable=True),
    sa.Column('filhos', sa.Integer(), nullable=True),
    sa.Column('batizado', sa.Boolean(), nullable=True),
    sa.Column('data_batismo', sa.Date(), nullable=True),
    sa.Column('ministerio', sa.String(length=100), nullable=True),
    sa.Column('foto', sa.String(length=100), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ministerio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('lider', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('metodo', sa.String(length=20), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('membro_id', sa.Integer(), nullable=True),
    sa.Column('is_fixo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['membro_id'], ['membro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('nivel_acesso', sa.Integer(), nullable=True),
    sa.Column('is_secretaria', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('membro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['membro_id'], ['membro.id'], name='fk_user_membro'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('compromisso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.String(length=20), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('membro_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['membro_id'], ['membro.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagem_enviada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('destinatario', sa.String(length=200), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=True),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagem_enviada')
    op.drop_table('compromisso')
    op.drop_table('user')
    op.drop_table('transacao')
    op.drop_table('ministerio')
    op.drop_table('membro')
    op.drop_table('evento')
    op.drop_table('custos_fixos')
    op.drop_table('configuracao_financeira')
    op.drop_table('configuracao')
    # ### end Alembic commands ###
