"""Corrige nome da FK membro_id e adiciona is_admin

Revision ID: fbb7163c56be
Revises: 16fb6d9f5ead
Create Date: 2025-11-11 22:57:50.847867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb7163c56be'
down_revision = '16fb6d9f5ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('membro_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_membro', 'membro', ['membro_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_membro', type_='foreignkey')
        batch_op.drop_column('membro_id')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
